# Generated by Django 2.2.5 on 2019-11-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha de publicacion')),
                ('titulo', models.CharField(help_text='Ingrese el titulo del anuncio', max_length=30)),
                ('descripcion', models.TextField(help_text='Ingrese el anuncion que quiere realizar')),
                ('dirigido', models.CharField(choices=[('padres', 'Padres'), ('alumno', 'Alumnos'), ('publico', 'Publico')], help_text='Ingrese a las personas a las que va dirigido el anuncio', max_length=7)),
                ('tipo', models.CharField(choices=[('importante', 'Importante'), ('evento', 'Evento'), ('comunicado', 'Comunicado'), ('otros', 'Otros')], help_text='Ingrese el tipo de anuncio que se quiere publicar', max_length=10)),
            ],
            options={
                'verbose_name': 'anuncio',
                'verbose_name_plural': 'anuncios',
                'ordering': ['-fecha'],
            },
        ),
    ]
