# Generated by Django 2.2.5 on 2019-10-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='dirigido',
            field=models.CharField(choices=[('padres', 'Padres'), ('alumno', 'Alumnos'), ('publico', 'Publico')], help_text='Ingrese a las personas a las que va dirigido el anuncio', max_length=7),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(choices=[('importante', 'Importante'), ('evento', 'Evento'), ('comunicado', 'Comunicado'), ('otros', 'Otros')], help_text='Ingrese el tipo de anuncio que se quiere publicar', max_length=10),
        ),
    ]
