# Generated by Django 2.2.5 on 2019-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaltaProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(help_text='Ingrese el nombre del profesor', max_length=50)),
                ('materia', models.CharField(help_text='Ingrese nombre de la materia', max_length=50)),
                ('curso', models.CharField(help_text='Ingrese el curso donde va a ocurrir la auscencia', max_length=50)),
                ('fecha', models.DateField(help_text='Ingrese fecha que ocurrira la falta del profesor')),
                ('turno', models.CharField(help_text='Ingrese turno en el que el profesor falta', max_length=50)),
            ],
            options={
                'verbose_name': 'faltaprofesor',
                'verbose_name_plural': 'faltasprofesores',
                'ordering': ['-fecha'],
            },
        ),
    ]
