# Generated by Django 2.2.5 on 2019-11-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorasInstitucionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], help_text='Ingrese el dia que se realizan las horas institucionales', max_length=10, verbose_name='Dia de la Semana')),
                ('desde', models.TimeField(help_text='Ingrese la hora de inicio de las horas institucionales')),
                ('hasta', models.TimeField(help_text='Ingrese la hora de fin de las horas institucionales')),
            ],
            options={
                'verbose_name': 'horainstitucional',
                'verbose_name_plural': 'horasinstitucionales',
                'ordering': ['-desde'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('profesor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(help_text='Ingrese nombre del profesor que dara la clase de consulta', max_length=50)),
                ('materia', models.CharField(help_text='Ingrese el nombre de la materia o jefatura de lo que se va a dar en la clase de consulta', max_length=20)),
                ('desde_lunes', models.TimeField(blank=True, help_text='Ingrese el dia y el horario de inicio de la clase del lunes', null=True)),
                ('hasta_lunes', models.TimeField(blank=True, help_text='Ingrese el dia y el horario de fin de la clase del lunes', null=True)),
                ('desde_martes', models.TimeField(blank=True, help_text='Ingrese el dia y el horario de inicio de la clase del martes', null=True)),
                ('hasta_martes', models.TimeField(blank=True, help_text='Ingrese el dia y el horario de fin de la clase del martes', null=True)),
                ('desde_miercoles', models.TimeField(blank=True, help_text='Ingrese el dia y el horario de inicio de la clase del miercoles', null=True)),
                ('hasta_miercoles', models.TimeField(blank=True, help_text='Ingrese el dia y el horario de fin de la clase del miercoles', null=True)),
                ('desde_jueves', models.TimeField(blank=True, help_text='Ingrese el dia y el horario de inicio de la clase del jueves', null=True)),
                ('hasta_jueves', models.TimeField(blank=True, help_text='Ingrese el dia y el horario de fin de la clase del jueves', null=True)),
                ('desde_viernes', models.TimeField(blank=True, help_text='Ingrese el dia y el horario de inicio de la clase del viernes', null=True)),
                ('hasta_viernes', models.TimeField(blank=True, help_text='Ingrese el dia y el horario de fin de la clase del viernes', null=True)),
                ('horas_institucionales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.HorasInstitucionales')),
            ],
            options={
                'verbose_name': 'horarioconsulta',
                'verbose_name_plural': 'horariosconsultas',
                'ordering': ['materia'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], max_length=50)),
                ('J1', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='J1Id', to='horario.Materia')),
                ('J2', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='J2Id', to='horario.Materia')),
                ('J3', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='J3Id', to='horario.Materia')),
                ('J4', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='J4Id', to='horario.Materia')),
                ('J5', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='J5Id', to='horario.Materia')),
                ('J6', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='J6Id', to='horario.Materia')),
                ('J7', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='J7Id', to='horario.Materia')),
                ('L1', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='L1Id', to='horario.Materia')),
                ('L2', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='L2Id', to='horario.Materia')),
                ('L3', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='L3Id', to='horario.Materia')),
                ('L4', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='L4Id', to='horario.Materia')),
                ('L5', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='L5Id', to='horario.Materia')),
                ('L6', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='L6Id', to='horario.Materia')),
                ('L7', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='L7Id', to='horario.Materia')),
                ('M1', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M1Id', to='horario.Materia')),
                ('M2', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M2Id', to='horario.Materia')),
                ('M3', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M3Id', to='horario.Materia')),
                ('M4', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M4Id', to='horario.Materia')),
                ('M5', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M5Id', to='horario.Materia')),
                ('M6', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M6Id', to='horario.Materia')),
                ('M7', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M7Id', to='horario.Materia')),
                ('V1', models.ForeignKey(blank=True, default='-', help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='V1Id', to='horario.Materia')),
                ('V2', models.ForeignKey(blank=True, default='-', help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='V2Id', to='horario.Materia')),
                ('V3', models.ForeignKey(blank=True, default='-', help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='V3Id', to='horario.Materia')),
                ('V4', models.ForeignKey(blank=True, default='-', help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='V4Id', to='horario.Materia')),
                ('V5', models.ForeignKey(blank=True, default='-', help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='V5Id', to='horario.Materia')),
                ('V6', models.ForeignKey(blank=True, default='-', help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='V6Id', to='horario.Materia')),
                ('V7', models.ForeignKey(blank=True, default='-', help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='V7Id', to='horario.Materia')),
                ('X1', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='X1Id', to='horario.Materia')),
                ('X2', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='X2Id', to='horario.Materia')),
                ('X3', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='X3Id', to='horario.Materia')),
                ('X4', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='X4Id', to='horario.Materia')),
                ('X5', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='X5Id', to='horario.Materia')),
                ('X6', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='X6Id', to='horario.Materia')),
                ('X7', models.ForeignKey(blank=True, help_text='Seleccione la materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='X7Id', to='horario.Materia')),
            ],
        ),
    ]
