# Generated by Django 2.2.6 on 2019-11-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorasInstitucionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], help_text='Ingrese el dia que se realizan las horas institucionales', max_length=10, verbose_name='Dia de la Semana')),
                ('hasta', models.TimeField(help_text='Ingrese la hora de fin de las horas institucionales')),
                ('desde', models.TimeField(help_text='Ingresela hora de inicio de las horas institucionales')),
            ],
            options={
                'verbose_name': 'horainstitucional',
                'verbose_name_plural': 'horasinstitucionales',
                'ordering': ['-desde'],
            },
        ),
        migrations.CreateModel(
            name='HorarioConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(help_text='Ingrese nombre del profesor que dara la clase de consulta', max_length=50)),
                ('materia', models.CharField(help_text='Ingrese el nombre de la materia o jefatura de lo que se va a dar en la clase de consulta', max_length=20)),
                ('desde', models.TimeField(help_text='Ingrese el dia y el horario de inicio de la clase')),
                ('hasta', models.TimeField(help_text='Ingrese el dia y el horario de fin de la clase')),
                ('horas_institucionales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.HorasInstitucionales')),
            ],
            options={
                'verbose_name': 'horarioconsulta',
                'verbose_name_plural': 'horariosconsultas',
                'ordering': ['-desde'],
            },
        ),
    ]
