# Generated by Django 2.2.6 on 2019-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioconsulta',
            name='desde_jueves',
            field=models.TimeField(blank=True, help_text='Ingrese el dia y el horario de inicio de la clase del jueves', null=True),
        ),
        migrations.AlterField(
            model_name='horarioconsulta',
            name='desde_lunes',
            field=models.TimeField(blank=True, help_text='Ingrese el dia y el horario de inicio de la clase del lunes', null=True),
        ),
        migrations.AlterField(
            model_name='horarioconsulta',
            name='desde_martes',
            field=models.TimeField(blank=True, help_text='Ingrese el dia y el horario de inicio de la clase del martes', null=True),
        ),
        migrations.AlterField(
            model_name='horarioconsulta',
            name='desde_miercoles',
            field=models.TimeField(blank=True, help_text='Ingrese el dia y el horario de inicio de la clase del miercoles', null=True),
        ),
        migrations.AlterField(
            model_name='horarioconsulta',
            name='desde_viernes',
            field=models.TimeField(blank=True, help_text='Ingrese el dia y el horario de inicio de la clase del viernes', null=True),
        ),
        migrations.AlterField(
            model_name='horarioconsulta',
            name='hasta_jueves',
            field=models.TimeField(blank=True, help_text='Ingrese el dia y el horario de fin de la clase del jueves', null=True),
        ),
        migrations.AlterField(
            model_name='horarioconsulta',
            name='hasta_lunes',
            field=models.TimeField(blank=True, help_text='Ingrese el dia y el horario de fin de la clase del lunes', null=True),
        ),
        migrations.AlterField(
            model_name='horarioconsulta',
            name='hasta_martes',
            field=models.TimeField(blank=True, help_text='Ingrese el dia y el horario de fin de la clase del martes', null=True),
        ),
        migrations.AlterField(
            model_name='horarioconsulta',
            name='hasta_miercoles',
            field=models.TimeField(blank=True, help_text='Ingrese el dia y el horario de fin de la clase del miercoles', null=True),
        ),
        migrations.AlterField(
            model_name='horarioconsulta',
            name='hasta_viernes',
            field=models.TimeField(blank=True, help_text='Ingrese el dia y el horario de fin de la clase del viernes', null=True),
        ),
    ]
