# Generated by Django 2.2.6 on 2019-11-04 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(blank=True, help_text='Ingrese su primer nombre.', max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, help_text='Ingrese su segundo nombre', max_length=50)),
                ('apellido', models.CharField(blank=True, help_text='Ingrese su apellido.', max_length=50)),
                ('correo', models.EmailField(blank=True, help_text='Ingrese su correo electrónico.', max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
