# Generated by Django 2.2.6 on 2019-10-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20191018_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='nombre',
        ),
        migrations.AddField(
            model_name='alumno',
            name='primer_nombre',
            field=models.CharField(blank=True, help_text='Ingrese su primer nombre.', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='segundo_nombre',
            field=models.CharField(blank=True, help_text='Ingrese su segundo nombre', max_length=50),
        ),
    ]
